### ISSUE TITLE
Issues with setting up a Staking Channel

### ISSUE THREAD

**Issue by paulbrasted** [Nexusoft/Legacy#98]
I liked the looked of this coin and the idea of a staking channel so to that end I have bought around 1200 plus nexus, download the blockchain onto my windows 10  SSD and  download the partial blockchain and then synchronized. Everything works OK and funds were transferred and show OK. To the end of setting up the Staking channel I have unlocked my wallet for minting and have now been running the nexus-qt for around 8 hours.  On the bottom right of the nexus-qt gui it show a green tick and that I have 17 connections to nexus . The indicatpr that I am staking though is not showing as a clock and the mouse over reads "Average age of balance less than 72 hours Waiting to begin staking....."

I am beginning to think that it is not working .. I have opened up port  9323 . How long do I have to wait for skaking to begin . I note issue 93 but it did not seem to be resolved 

I an running the latest nexus-qt 2.5.5

Thank you for any help

**Comment by paulscreen** [comment]
Staking doesn’t begin until your coins have an average age of more than 72 hours. That means you will need to wait at least 3 days before your first reward. Thereafter the frequency of your staking rewards depends on your trust (which builds over time), the amount of coins you have, and the current difficulty of the staking channel. These combined may mean there might be several days between rewards, however remember the reward is based on your stake rate pro rated over the time since your last payment, so it doesn’t matter how often you mine a stake block as long as you find one within 72 hours of the last.

**Comment by paulbrasted** [comment]
Thanks for that..perhaps the 72 hour thing should be included in the docs on setting up staking on Nexus earth...it's a long time to wonder whether things are working...I want to build up trust as well ha
